[workspace]
members = ["npm:doppler_ui", "cargo:doppler"]

# Config for 'cargo dist'
[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Extra static files to include in each App (path relative to this Cargo.toml's dir)
include = ["./examples", "./doppler/config", "./doppler_ui/ui_config"]
# Path that installers should place binaries in
install-path = ["$DOPPLER_HOME/", "~/.doppler"]
# Whether to install an updater program
install-updater = false
# Publish jobs to run in CI
pr-run-mode = "plan"
