version: '3.8'
services:
  doppler-bitcoind-miner-bd1:
    image: polarlightning/bitcoind:25.0
    container_name: doppler-bitcoind-miner-bd1
    ports:
    - 9094:9091
    volumes:
    - /home/teebz/repos/doppler/data/bd1/.bitcoin:/home/bitcoin/.bitcoin:rw
    networks:
    - doppler
    command:
    - -addnode=doppler-bitcoind-bd2:9096
    - -addnode=doppler-bitcoind-bd3:9101
    env_file: .env
  doppler-bitcoind-bd2:
    image: polarlightning/bitcoind:25.0
    container_name: doppler-bitcoind-bd2
    ports:
    - 9099:9096
    volumes:
    - /home/teebz/repos/doppler/data/bd2/.bitcoin:/home/bitcoin/.bitcoin:rw
    networks:
    - doppler
    command:
    - -addnode=doppler-bitcoind-miner-bd1:9091
    - -addnode=doppler-bitcoind-bd3:9101
    env_file: .env
  doppler-bitcoind-bd3:
    image: polarlightning/bitcoind:25.0
    container_name: doppler-bitcoind-bd3
    ports:
    - 9104:9101
    volumes:
    - /home/teebz/repos/doppler/data/bd3/.bitcoin:/home/bitcoin/.bitcoin:rw
    networks:
    - doppler
    command:
    - -addnode=doppler-bitcoind-miner-bd1:9091
    - -addnode=doppler-bitcoind-bd2:9096
    env_file: .env
  doppler-lnd1:
    image: polarlightning/lnd:0.16.2-beta
    container_name: doppler-lnd1
    ports:
    - 9105:8080
    - 9106:10009
    volumes:
    - /home/teebz/repos/doppler/data/lnd1/.lnd:/home/lnd/.lnd:rw
    networks:
    - doppler
    env_file: .env
  doppler-lnd2:
    image: polarlightning/lnd:0.16.2-beta
    container_name: doppler-lnd2
    ports:
    - 9107:8080
    - 9108:10009
    volumes:
    - /home/teebz/repos/doppler/data/lnd2/.lnd:/home/lnd/.lnd:rw
    networks:
    - doppler
    env_file: .env
  doppler-lnd3:
    image: polarlightning/lnd:0.16.2-beta
    container_name: doppler-lnd3
    ports:
    - 9109:8080
    - 9110:10009
    volumes:
    - /home/teebz/repos/doppler/data/lnd3/.lnd:/home/lnd/.lnd:rw
    networks:
    - doppler
    env_file: .env
networks:
  doppler: {}
